apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: LOG_LEVEL
          value: "error"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
            httpGet:
              path: /
              port: 80
        livenessProbe:
            tcpSocket:
              port: 80