apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
    web.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /web
        pathType: Prefix
        backend:
          service:
            name: web
            port: 
              number: 8080
